export const HOME_SERVICES = [
  {
    image: "/mobile-app-development-service.png",
    img_width: "33px",
    img_height: "34px",
    title: "Mobile App Development",
    desc: "We help businesses grow with clear software solutions created by skilled experts from around the world.",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "GraphQL",
      "Next.js",
    ],
    alt_tag: "mobile app development image",
  },
  {
    image: "/web-app-development-service.png",
    title: "Web App Development",
    desc: "We help businesses grow with clear software solutions created by skilled experts from around the world.",
    img_width: "31.71px",
    img_height: "40px",
    tags: [
      "Flutter",
      "Dart",
      "Swift",
      "Kotlin",
      "Firebase",
      "SQL",
      "Node.js",
      "MongoDB",
    ],
    alt_tag: "web app development image",
  },
  {
    image: "/software-development.png",
    title: "Software Development",
    desc: "We help businesses grow with clear software solutions created by skilled experts from around the world.",
    img_width: "30px",
    img_height: "28px",
    tags: [
      "Research",
      "Logo Designing",
      "PS",
      "Merchandising",
      "Collateral",
      "Ai",
      "Social Media Setup",
    ],
    alt_tag: "software development image",
  },
  {
    image: "/ecommerce-development-service.png",
    title: "E-Commerce Development",
    desc: "We help businesses grow with clear software solutions created by skilled experts from around the world.",
    img_width: "28px",
    img_height: "28px",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Next.js",
      "MongoDB",
      "GraphQL",
      "Wordpress",
      "Shopify",
    ],
    alt_tag: "ecommerce development image",
  },
  {
    image: "/uiux-design-service.png",
    title: "UI/UX Design",
    desc: "We help businesses grow with clear software solutions created by skilled experts from around the world.",
    img_width: "34.17px",
    img_height: "28px",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Angular",
      "Tailwind CSS",
      "PHP",
      "Express.js",
      "Django",
      "Laravel",
      "AWS",
    ],
    alt_tag: "ui ux design image",
  },
  {
    image: "/branding-and-design-service.png",
    title: "Branding & Design",
    desc: "We help businesses grow with clear software solutions created by skilled experts from around the world.",
    img_width: "26px",
    img_height: "26px",
    tags: [
      "Audit",
      "Planning",
      "Support",
      "Upgrades",
      "Optimization",
      "Advisory",
    ],
    alt_tag: "branding & design image",
  },
  {
    image: "/digital-marketing-service.png",
    title: "Digital Marketing",
    desc: "We help businesses grow with clear software solutions created by skilled experts from around the world.",
    img_width: "29px",
    img_height: "26.1px",
    tags: ["SEO", "SMM", "Paid Campaigns", "ORM", "Content Creation"],
    alt_tag: "digital marketing image",
  },
  {
    image: "/maintenance-and-consutling-service.png",
    title: "Maintenance & Consulting ",
    desc: "We help businesses grow with clear software solutions created by skilled experts from around the world.",
    img_width: "36px",
    img_height: "26.31px",
    tags: [
      "Figma",
      "Wireframes",
      "Prototyping",
      "Brand Guide Lines",
      "Color Scheme",
      "Sketches",
    ],
    alt_tag: "maintenance & consulting image",
  },
];
