export const HOME_SERVICES = [
  {
    image: "/mobile-app-development-service.png",
    img_width: "33px",
    img_height: "34px",
    title: "Mobile App Development",
    desc: "You need an app that works smoothly and keeps the users engaged. A mobile app development company that helps you build fast, secure, and easy-to-use apps for IOS and Android. Every step is handled with care that makes sure that app fits your goals and reaches the right audience.",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "GraphQL",
      "Next.js",
    ],
    alt_tag: "mobile app development image",
    pageUrl: "/services/mobile-app-development-services",
  },
  {
    image: "/web-app-development-service.png",
    title: "Web App Development",
    desc: "Strong web app development keeps your business running efficiently. With web app development services, you get custom-built fast, secure, and user-friendly solutions for customers or internal teams. A well-designed web app improves workflows, boosts engagement, and delivers user experience.",
    img_width: "31.71px",
    img_height: "40px",
    tags: [
      "Flutter",
      "Dart",
      "Swift",
      "Kotlin",
      "Firebase",
      "SQL",
      "Node.js",
      "MongoDB",
    ],
    alt_tag: "web app development image",
    pageUrl: "/services/web-app-development-services",
  },
  {
    image: "/software-development.png",
    title: "Software Development",
    desc: "Your business is unique, and your software should be too. With custom software development services, get tailored solutions that could fix your exact needs. Whether it’s automating tasks, improving efficiency, or scaling operations, the correct software could make a difference. There are no unnecessary features, just the tools that are used perfectly and built specifically for your business requirements.",
    img_width: "30px",
    img_height: "28px",
    tags: [
      "Research",
      "Logo Designing",
      "PS",
      "Merchandising",
      "Collateral",
      "Ai",
      "Social Media Setup",
    ],
    alt_tag: "software development image",
    pageUrl: "/",
  },
  {
    image: "/ecommerce-development-service.png",
    title: "E-Commerce Development",
    desc: "Selling online should be simple and effective with e-commerce app development services. Create an easy-to-use store that helps customers find, buy, and return with confidence. Create a secure and fast mobile-friendly platform that ensures smooth shopping experiences. Build an online store that grows your business and keeps customers coming back.",
    img_width: "28px",
    img_height: "28px",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Next.js",
      "MongoDB",
      "GraphQL",
      "Wordpress",
      "Shopify",
    ],
    alt_tag: "ecommerce development image",
    pageUrl: "/",
  },
  {
    image: "/uiux-design-service.png",
    title: "UI/UX Design",
    desc: "Good design makes things easier to use. UI/UX design services create smooth and appealing experiences for websites or apps. Easy navigation, clear layouts, engaging designs keep users happy and make them want to experience again. A great interface improves satisfaction and boosts conversions.",
    img_width: "34.17px",
    img_height: "28px",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Angular",
      "Tailwind CSS",
      "PHP",
      "Express.js",
      "Django",
      "Laravel",
      "AWS",
    ],
    alt_tag: "ui ux design image",
    pageUrl: "/",
  },
  {
    image: "/branding-and-design-service.png",
    title: "Branding & Designing",
    desc: "Your brand is how people remember you. With branding & designing services, create a strong identity that connects with the customers. From the logos to the entire brand strategy, every small detail matters. Clear, creative, and eye-catching designs that helps build trust, and make you stand out from the competition.",
    img_width: "26px",
    img_height: "26px",
    tags: [
      "Audit",
      "Planning",
      "Support",
      "Upgrades",
      "Optimization",
      "Advisory",
    ],
    alt_tag: "branding & design image",
    pageUrl: "/",
  },
  {
    image: "/digital-marketing-service.png",
    title: "Digital Marketing",
    desc: "Reaching the right online audience takes approach and ability. With digital marketing services, visibility can be boosted through SEO, paid ads, and social media. Also, drive traffic and lead generation and turn your visitors into loyal customers. A strong digital presence that helps your business grow and stay ahead in a competitive online world.",
    img_width: "29px",
    img_height: "26.1px",
    tags: ["SEO", "SMM", "Paid Campaigns", "ORM", "Content Creation"],
    alt_tag: "digital marketing image",
    pageUrl: "/",
  },
  {
    image: "/maintenance-and-consutling-service.png",
    title: "Maintenance & Support ",
    desc: "It is essential to keep your software up to date. With maintenance and consulting services, you can get expert support, daily updates, and security fixes to make sure everything runs smoothly. Do you need expert guidance regarding tech strategy? Get clear advice to make well-informed choices and improve performance without any technical issues.",
    img_width: "36px",
    img_height: "26.31px",
    tags: [
      "Figma",
      "Wireframes",
      "Prototyping",
      "Brand Guide Lines",
      "Color Scheme",
      "Sketches",
    ],
    alt_tag: "maintenance & consulting image",
    pageUrl: "/",
  },
];
