export const REVIEWS = [
  {
    text: "I needed a website but wasn't sure where to start. The Launchbox Global team guided me through the entire process and created exactly what I expected. Super smooth experience.",
    author: "Sarah Mitchell",
    designation: "CEO of ThreadCraft Co.",
    image: "/review-girl.webp",
  },
  {
    text: "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result.",
    author: "Michael Reynolds",
    designation: "CEO of PureGlow Labs",
    image: "/review-01.webp",
  },
  {
    text: " They took care of everything from beginning to end. The app works perfectly, and we are really pleased with the outcome!",
    author: "Daniel Foster",
    designation: "Founder &  CTO of GlowLuxe Beauty",
    image: "/review-03.webp",
  },
  {
    text: "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
    author: "Emily Walker",
    designation: "IT Project  Manager of SavoryBite Foods",
    image: "/review-girl-2.webp",
  },
  {
    text: "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result",
    author: "David Lee",
    designation: "Co-founder & President of Dealsparx",
    image: "/review-04.webp",
  },
  //
  {
    text: "I needed a website but wasn't sure where to start. The Launchbox Global team guided me through the entire process and created exactly what I expected. Super smooth experience.",
    author: "Sarah Mitchell",
    designation: "CEO of ThreadCraft Co.",
    image: "/review-girl.webp",
  },
  {
    text: "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result.",
    author: "Michael Reynolds",
    designation: "CEO of PureGlow Labs",
    image: "/review-01.webp",
  },
  {
    text: " They took care of everything from beginning to end. The app works perfectly, and we are really pleased with the outcome!",
    author: "Daniel Foster",
    designation: "Founder &  CTO of GlowLuxe Beauty",
    image: "/review-03.webp",
  },
  {
    text: "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
    author: "Emily Walker",
    designation: "IT Project  Manager of SavoryBite Foods",
    image: "/review-girl-2.webp",
  },
  {
    text: "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result",
    author: "David Lee",
    designation: "Co-founder & President of Dealsparx",
    image: "/review-04.webp",
  },

  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
  // "Highly recommend! They created a user-friendly app that our consumers adore, understood our goal, and offered insightful advice.",
  // "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result",
  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
  // "Highly recommend! They created a user-friendly app that our consumers adore, understood our goal, and offered insightful advice.",
  // "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result",
  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
  // "Highly recommend! They created a user-friendly app that our consumers adore, understood our goal, and offered insightful advice.",
  // "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result",
  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
  // "Highly recommend! They created a user-friendly app that our consumers adore, understood our goal, and offered insightful advice.",
  // "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result",
  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
  // "Highly recommend! They created a user-friendly app that our consumers adore, understood our goal, and offered insightful advice.",
  // "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result",
  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
  // "Highly recommend! They created a user-friendly app that our consumers adore, understood our goal, and offered insightful advice.",
  // "The Launchbox Global team was outstanding! Fast response, honest communication, and an excellent end result",
  // "The entire process, from design to development, went smoothly. Thanks to their knowledge, our app is now operating without a glitch",
];
