export const FLUTTER_TECH_STACK = [
  {
    title: "Flutter SDK",
    icon: "/flutter/flutter-icon.png",
    width: 32,
    height: 30,
    boxWidth: 190,
  },
  {
    title: "Dart",
    icon: "/flutter/dart-icon.png",
    width: 32,
    height: 30,
    boxWidth: 122,
  },
  {
    title: "Firebase",
    icon: "/flutter/firebase-icon.png",
    width: 32,
    height: 30,
    boxWidth: 160,
  },
  {
    title: "GetX",
    icon: "/flutter/getx-icon.png",
    width: 32,
    height: 30,
    boxWidth: 130,
  },
  {
    title: "Riverpod",
    icon: "/flutter/riverpod-icon.png",
    width: 32,
    height: 30,
    boxWidth: 162,
  },
  {
    title: "Bloc",
    icon: "/flutter/bloc-icon.png",
    width: 32,
    height: 30,
    boxWidth: 124,
  },
  {
    title: "REST APIs",
    icon: "/flutter/rest-api-icon.png",
    width: 32,
    height: 30,
    boxWidth: 174,
  },
  {
    title: "GraphQL",
    icon: "/flutter/graphql-icon.png",
    width: 32,
    height: 30,
    boxWidth: 168,
  },
  {
    title: "SQLite ",
    icon: "/flutter/sqlite.png",
    width: 32,
    height: 30,
    boxWidth: 142,
  },
  {
    title: "Hive",
    icon: "/flutter/hive-icon.png",
    width: 32,
    height: 30,
    boxWidth: 119,
  },
  {
    title: "ObjectBox",
    icon: "/flutter/objectbox-icon.png",
    width: 32,
    height: 30,
    boxWidth: 178,
  },
  {
    title: "CI/CD",
    icon: "/flutter/cicd-icon.png",
    width: 32,
    height: 30,
    boxWidth: 162,
  },
  {
    title: "GitHub Actions",
    icon: "/flutter/github-actions.png",
    width: 32,
    height: 30,
    boxWidth: 223,
  },
  {
    title: "Sentry",
    icon: "/flutter/sentry-icon.png",
    width: 32,
    height: 30,
    boxWidth: 142,
  },
];
